check filename pascal case

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,11 +6,8 @@ on:
       - main
 
 jobs:
-  # ------------------------------------------------------------------------------------------------------------------------------------------------
-  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
-  # ------------------------------------------------------------------------------------------------------------------------------------------------
   changed_files:
-    runs-on: ubuntu-latest # windows-latest || macos-latest
+    runs-on: ubuntu-latest
     name: Test changed-files
     steps:
       - uses: actions/checkout@v4
@@ -18,9 +15,7 @@ jobs:
       - name: Get changed files
         id: changed-files
         uses: tj-actions/changed-files@v45
-        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
-        # with:
-        #   since_last_remote_commit: true
+        # 옵션 예시: since_last_remote_commit: true
 
       - name: List all changed files
         env:
@@ -29,3 +24,23 @@ jobs:
           for file in ${ALL_CHANGED_FILES}; do
             echo "$file was changed"
           done
+
+      - name: Check for files starting with uppercase letter
+        env:
+          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
+        run: |
+          error_found=0
+          for file in ${ALL_CHANGED_FILES}; do
+            filename=$(basename "$file")
+            if [[ $filename =~ ^[A-Z] ]]; then
+              echo "Error: '$file' starts with an uppercase letter."
+              error_found=1
+            fi
+          done
+          if [ $error_found -ne 0 ]; then
+            echo "One or more files have names starting with uppercase letters. Failing the build."
+            exit 1
+          fi
+
+      - name: check
+        run: echo 'not run'
